// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'row': string;
  'uploadFile__hiddenButton': string;
  'uploadFile__visibleButton': string;
}
export const cssExports: CssExports;
export default cssExports;
