// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconWrapper': string;
  'sizeWrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
