// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'diagramBody': string;
  'diagramData': string;
  'diagramWrapper': string;
  'moreIcon': string;
  'spike': string;
  'topOverflow': string;
  'trendingIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
