// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbar': string;
  'sidebar': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
