// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'addBtn__icon': string;
  'filterBtn': string;
  'folders': string;
  'folders__item': string;
  'header': string;
  'header__left': string;
  'header__right': string;
  'importantFolder': string;
  'importantFolder__actions': string;
  'importantFolder__body': string;
  'importantFolder__folderIcon': string;
  'importantFolder__footer': string;
  'importantFolder__name': string;
  'importantFolder__size': string;
  'importantFolder__user': string;
  'importantFolder__users': string;
  'importantFolder__users__addIcon': string;
  'importantFolder__wrapper': string;
  'labels': string;
  'labels__item': string;
  'regularFolder': string;
  'regularFolder__folderIcon': string;
  'regularFolder__folderIconWrapper': string;
  'regularFolder__footer': string;
  'regularFolder__size': string;
  'regularFolder__wrapper': string;
  'status': string;
  'status__icon': string;
  'status__measure': string;
  'status__value': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
