// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'listItem': string;
  'listItem__iconWrapper': string;
  'listItem__nameWrapper': string;
  'listItem__name_and_iconWrapper': string;
  'listItem__newBtn': string;
  'noteIcon': string;
  'viewAllBtn': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
