// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'searchBlock': string;
  'searchBlock__iconWrapper': string;
  'searchBlock__searchInput': string;
  'wrapper': string;
  'wrapper__left': string;
  'wrapper__right': string;
}
export const cssExports: CssExports;
export default cssExports;
