// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'option': string;
  'optionLink': string;
  'options': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
