// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fileInput': string;
  'uploadArea': string;
  'uploadArea__drag': string;
  'uploadLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
