// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'size10': string;
  'size100': string;
  'size110': string;
  'size120': string;
  'size130': string;
  'size140': string;
  'size150': string;
  'size160': string;
  'size170': string;
  'size180': string;
  'size190': string;
  'size20': string;
  'size200': string;
  'size30': string;
  'size40': string;
  'size50': string;
  'size60': string;
  'size70': string;
  'size80': string;
  'size90': string;
}
export const cssExports: CssExports;
export default cssExports;
