// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ldsEllipsis': string;
  'ldsEllipsis1': string;
  'ldsEllipsis2': string;
  'ldsEllipsis3': string;
  'loader': string;
}
export const cssExports: CssExports;
export default cssExports;
